uploads = []
outputs = []

[[generated]]
id = "OADfrYbLjOygXanqFmf-C"
uri = "file://artifacts/preventivo-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8wixyJtXAFJYh3Im9_pkp"
uri = "file://artifacts/preventivo-mobile/assets/images/splash.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Fsl84cJsna2veTxNg6DqZ"
uri = "file://artifacts/prevai-demo-video/public/images/craftsman-workbench.png"
type = "image"
title = "Craftsman hands on workbench"
