// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/prevai-redesign/CrmRedesign.tsx": () => import("../components/mockups/prevai-redesign/CrmRedesign.tsx"),
  "./components/mockups/prevai-redesign/DashboardRedesign.tsx": () => import("../components/mockups/prevai-redesign/DashboardRedesign.tsx"),
  "./components/mockups/prevai-redesign/HomeRedesign.tsx": () => import("../components/mockups/prevai-redesign/HomeRedesign.tsx"),
  "./components/mockups/prevai-home-deepdive/Preview.tsx": () => import("../components/mockups/prevai-home-deepdive/Preview.tsx")
};
