// V2-2: il motore fiscale vive in @workspace/config (regime IVA italiano,
// province italiane). Questo modulo lo ri-esporta per non spezzare gli
// import esistenti (`from "@workspace/db"`) ereditati da QuoteAI.
export {
  type IvaCode,
  type TaxProfileCode,
  type TaxComponent,
  type TaxProfile,
  type TaxBreakdownLine,
  TAX_PROFILES,
  DEFAULT_TAX_CODE,
  DEFAULT_TAX_RATE,
  FORFETTARIO_NOTE,
  BOLLO,
  isTaxCode,
  getTaxProfile,
  taxProfileForRate,
  computeTax,
  splitTaxRate,
  quoteTaxLines,
  bolloDovuto,
  PROVINCE_ITALIANE,
  REGIONI,
  type Regione,
  type Provincia,
  isProvinceCode,
  normalizeProvince,
  provinceName,
  regioneDiProvincia,
  normalizeRegione,
} from "@workspace/config";
