// V2-2: il motore fiscale vive in @workspace/config (regime IVA italiano,
// province italiane). Questo modulo lo ri-esporta per non spezzare gli
// import esistenti (`from "@workspace/db"`) ereditati da QuoteAI.
export {
  type IvaCode,
  type TaxProfileCode,
  type TaxComponent,
  type TaxProfile,
  type TaxBreakdownLine,
  TAX_PROFILES,
  DEFAULT_TAX_CODE,
  DEFAULT_TAX_RATE,
  FORFETTARIO_NOTE,
  BOLLO,
  isTaxCode,
  getTaxProfile,
  taxProfileForRate,
  computeTax,
  splitTaxRate,
  quoteTaxLines,
  bolloDovuto,
  PROVINCE_ITALIANE,
  REGIONI,
  type Regione,
  type Provincia,
  isProvinceCode,
  normalizeProvince,
  provinceName,
  regioneDiProvincia,
  normalizeRegione,
} from "@workspace/config";

// A-1: codifiche FatturaPA (tipo documento, regime fiscale, natura, modalità
// di pagamento, controlli su P. IVA / C.F. / codice destinatario / IBAN).
export {
  type TipoDocumento,
  type RegimeFiscale,
  type Natura,
  type EsigibilitaIva,
  type ModalitaPagamento,
  type CondizioniPagamento,
  type RigaIvaFatturaPa,
  type StatoSdi,
  TIPI_DOCUMENTO,
  REGIMI_FISCALI,
  REGIME_FISCALE_DEFAULT,
  NATURE,
  MODALITA_PAGAMENTO,
  STATI_SDI,
  STATI_SDI_EMESSA,
  STATI_SDI_FINALI,
  STATI_SDI_LABEL,
  STATI_SDI_AZIONE,
  ERRORI_SDI,
  CODICE_DESTINATARIO_PRIVATO,
  CODICE_DESTINATARIO_ESTERO,
  isRegimeFiscale,
  regimeSenzaIva,
  rigaIva,
  modalitaPagamentoPerMetodo,
  validaCodiceDestinatario,
  isCodiceDestinatarioPa,
  validaPec,
  validaPartitaIva,
  normalizzaPartitaIva,
  validaCodiceFiscale,
  normalizzaCodiceFiscale,
  codiceFiscaleCanonico,
  validaCap,
  validaIban,
  normalizzaIban,
  progressivoInvio,
  nomeFileFattura,
  importo,
  quantita,
  dataFattura,
  descrizioneErroreSdi,
} from "@workspace/config";
